(() => {
  "use strict";
  const scenes = Array.from(document.querySelectorAll(".scene"));
  const state = {currentScene:0,entered:false,musicPlaying:false,reducedMotion:false,journeyOpened:new Set(),notesOpened:new Set(),letterOpened:false,fearChosen:false};
  const journeyContent=[
    {kicker:"The Beginning",title:"Semuanya pernah dimulai dari judul, pertanyaan, dan banyak hal yang belum jelas.",text:"Saat itu mungkin kamu belum tahu sejauh apa perjalanan ini akan berjalan. Tapi kamu tetap memilih untuk memulainya.",icon:"✦"},
    {kicker:"The Process",title:"Ada teori, data, revisi, rasa lelah, dan banyak overthinking.",text:"Tidak semuanya berjalan sesuai rencana. Ada bagian yang harus diperbaiki, dipahami ulang, dan diselesaikan pelan-pelan.",icon:"⌁"},
    {kicker:"The Persistence",title:"Kamu tetap kembali mengerjakannya, bahkan saat rasa takut lebih besar daripada rasa percaya diri.",text:"Mungkin kamu tidak selalu merasa kuat. Tetapi tetap melanjutkan ketika sedang takut juga merupakan bentuk keberanian.",icon:"♡"},
    {kicker:"The Final Step",title:"Sekarang kamu berada di titik yang dulu terasa sangat jauh.",text:"Besok bukan awal dari perjuanganmu. Besok adalah salah satu hasil dari semua perjuangan yang sudah kamu lakukan.",icon:"→"}
  ];
  const noteContent=[
    {kicker:"When You Feel Nervous",title:"Grogi bukan berarti kamu tidak siap.",text:"Itu hanya berarti momen ini penting buat kamu. Tarik napas perlahan dan biarkan tubuhmu menyusul ketenangan pikiranmu.",icon:"✿"},
    {kicker:"When the Lecturer Looks Strict",title:"Ekspresi tegas bukan tanda bahwa semuanya akan berjalan buruk.",text:"Dengarkan pertanyaannya sampai selesai. Fokus pada isi pertanyaannya, bukan pada ekspresi wajah dosennya.",icon:"❀"},
    {kicker:"When Your Mind Goes Blank",title:"Kamu tidak harus langsung menjawab.",text:"Berhenti sebentar, tarik napas, ulangi inti pertanyaannya di dalam pikiran, lalu mulai dari bagian yang paling kamu pahami.",icon:"✦"},
    {kicker:"When You Are Afraid of Being Wrong",title:"Satu jawaban yang kurang tepat tidak menghapus seluruh prosesmu.",text:"Jawab dengan jujur berdasarkan penelitianmu. Sidang bukan tuntutan untuk mengetahui semua hal di dunia.",icon:"♡"},
    {kicker:"When You Feel Insecure",title:"Kamu lebih mengenal penelitianmu daripada yang kamu sadari.",text:"Kamu sudah membaca, menyusun, memperbaiki, dan hidup bersama penelitian ini cukup lama.",icon:"☁"},
    {kicker:"From Ansa",title:"Besok kamu tidak masuk ke ruangan itu sendirian.",text:"Ada doa, dukungan, dan seseorang yang benar-benar percaya sama kamu. Aku tetap ada di sini, bahkan ketika rasa takutmu sedang paling berisik.",icon:"✉"}
  ];
  const fearResponses={lecturer:"Sikap tegas bukan berarti mereka ingin menjatuhkanmu. Fokuslah pada pertanyaan, bukan pada ekspresi wajahnya.",blank:"Diam beberapa detik tidak membuatmu gagal. Kamu boleh mengambil waktu sebelum menjawab.",wrong:"Sidang bukan ujian untuk membuktikan bahwa kamu mengetahui semuanya. Sidang adalah ruang untuk menjelaskan dan mempertanggungjawabkan penelitianmu.",nervous:"Suara sedikit bergetar masih tetap bisa menyampaikan jawaban yang baik.",all:"Wajar kalau semuanya terasa menakutkan malam ini. Tetapi rasa takut tidak menentukan kemampuanmu."};
  const el={appHeader:document.getElementById("appHeader"),sceneNavigation:document.getElementById("sceneNavigation"),enterButton:document.getElementById("enterButton"),homeButton:document.getElementById("homeButton"),previousButton:document.getElementById("previousButton"),nextButton:document.getElementById("nextButton"),sceneLabel:document.getElementById("sceneLabel"),progressBar:document.getElementById("sceneProgressBar"),sceneDots:document.getElementById("sceneDots"),musicButton:document.getElementById("musicButton"),musicIcon:document.getElementById("musicIcon"),motionButton:document.getElementById("motionButton"),backgroundMusic:document.getElementById("backgroundMusic"),photo:document.getElementById("amelPhoto"),photoFallback:document.getElementById("photoFallback"),journeyCards:Array.from(document.querySelectorAll(".journey-card")),journeyKicker:document.getElementById("journeyKicker"),journeyTitle:document.getElementById("journeyDetailTitle"),journeyText:document.getElementById("journeyDetailText"),journeyIcon:document.querySelector("#journeyDetail .detail-panel__icon"),journeyCompletion:document.getElementById("journeyCompletion"),calmNotes:Array.from(document.querySelectorAll(".calm-note")),noteKicker:document.getElementById("noteKicker"),noteTitle:document.getElementById("noteTitle"),noteText:document.getElementById("noteText"),noteIcon:document.querySelector("#noteDetail .detail-panel__icon"),fearPanel:document.getElementById("fearPanel"),fearOptions:Array.from(document.querySelectorAll("[data-fear]")),fearResponse:document.getElementById("fearResponse"),continueToLetter:document.getElementById("continueToLetter"),letterEnvelope:document.getElementById("letterEnvelope"),letterPaper:document.getElementById("letterPaper"),saveCourageButton:document.getElementById("saveCourageButton"),savedMessage:document.getElementById("savedMessage"),toast:document.getElementById("toast")};
  let toastTimer=null;
  function createSceneDots(){const f=document.createDocumentFragment();scenes.forEach((_,i)=>{const b=document.createElement("button");b.type="button";b.setAttribute("aria-label",`Buka chapter ${i+1}`);b.addEventListener("click",()=>{if(i===4&&!state.fearChosen){showToast("Pilih satu rasa takut terlebih dahulu.");return}goToScene(i)});f.appendChild(b)});el.sceneDots.replaceChildren(f)}
  function updateNavigation(){const p=((state.currentScene+1)/scenes.length)*100;el.sceneLabel.textContent=`Chapter ${state.currentScene+1} of ${scenes.length}`;el.progressBar.style.width=`${p}%`;Array.from(el.sceneDots.children).forEach((d,i)=>{const a=i===state.currentScene;d.classList.toggle("is-active",a);d.setAttribute("aria-current",a?"step":"false")});el.previousButton.disabled=state.currentScene===0;if(state.currentScene===scenes.length-1){el.nextButton.disabled=true;el.nextButton.innerHTML='Final Page <span aria-hidden="true">♡</span>'}else{el.nextButton.disabled=false;el.nextButton.innerHTML='Next <span aria-hidden="true">→</span>'}}
  function goToScene(index){const safe=Math.max(0,Math.min(index,scenes.length-1));scenes.forEach((s,i)=>{const a=i===safe;s.classList.toggle("is-active",a);s.hidden=!a;if(a)s.scrollTop=0});state.currentScene=safe;updateNavigation()}
  function showToast(message){clearTimeout(toastTimer);el.toast.textContent=message;el.toast.hidden=false;toastTimer=setTimeout(()=>{el.toast.hidden=true},2600)}
  async function toggleMusic(force=null){const play=typeof force==="boolean"?force:!state.musicPlaying;if(play){try{el.backgroundMusic.volume=.28;await el.backgroundMusic.play();state.musicPlaying=true;el.musicIcon.textContent="♫";el.musicButton.setAttribute("aria-label","Jeda musik");el.musicButton.title="Jeda musik"}catch{state.musicPlaying=false;el.musicIcon.textContent="♪";showToast("Tambahkan background-music.mp3 untuk mengaktifkan musik.")}}else{el.backgroundMusic.pause();state.musicPlaying=false;el.musicIcon.textContent="♪";el.musicButton.setAttribute("aria-label","Putar musik");el.musicButton.title="Putar musik"}}
  function handlePhotoFallback(){const show=()=>{el.photo.hidden=true;el.photoFallback.hidden=false};el.photoFallback.hidden=true;el.photo.addEventListener("error",show,{once:true});if(el.photo.complete&&el.photo.naturalWidth===0)show()}
  function openJourney(i){const c=journeyContent[i];state.journeyOpened.add(i);el.journeyCards.forEach((card,j)=>{const o=state.journeyOpened.has(j);card.classList.toggle("is-opened",o);card.querySelector("small").textContent=o?"Opened":"Tap to open"});el.journeyKicker.textContent=c.kicker;el.journeyTitle.textContent=c.title;el.journeyText.textContent=c.text;el.journeyIcon.textContent=c.icon;if(state.journeyOpened.size===journeyContent.length)el.journeyCompletion.hidden=false}
  function openNote(i){const c=noteContent[i];state.notesOpened.add(i);el.calmNotes.forEach((n,j)=>n.classList.toggle("is-opened",state.notesOpened.has(j)));el.noteKicker.textContent=c.kicker;el.noteTitle.textContent=c.title;el.noteText.textContent=c.text;el.noteIcon.textContent=c.icon;if(state.notesOpened.size===noteContent.length){el.fearPanel.hidden=false;el.fearPanel.scrollIntoView({behavior:state.reducedMotion?"auto":"smooth",block:"nearest"})}}
  function chooseFear(button){state.fearChosen=true;el.fearOptions.forEach(o=>o.classList.toggle("is-active",o===button));el.fearResponse.innerHTML=`${fearResponses[button.dataset.fear]}<br><strong>Your fear is loud. But it is not always right.</strong>`;el.continueToLetter.disabled=false}
  function openLetter(){if(state.letterOpened)return;state.letterOpened=true;el.letterEnvelope.classList.add("is-open");el.letterEnvelope.setAttribute("aria-expanded","true");setTimeout(()=>{el.letterEnvelope.hidden=true;el.letterPaper.hidden=false;el.letterPaper.scrollIntoView({behavior:state.reducedMotion?"auto":"smooth",block:"start"})},state.reducedMotion?10:470)}
  function saveCourage(){el.saveCourageButton.disabled=true;el.saveCourageButton.innerHTML='Saved <span aria-hidden="true">✓</span>';el.savedMessage.hidden=false;showToast("Courage saved. Love sent. Prayers included.")}
  el.enterButton.addEventListener("click",async()=>{state.entered=true;el.appHeader.classList.remove("is-hidden");el.sceneNavigation.classList.remove("is-hidden");await toggleMusic(true);goToScene(1)});el.homeButton.addEventListener("click",()=>goToScene(0));el.previousButton.addEventListener("click",()=>goToScene(state.currentScene-1));el.nextButton.addEventListener("click",()=>{if(state.currentScene===3&&!state.fearChosen){showToast("Pilih satu rasa takut terlebih dahulu.");return}goToScene(state.currentScene+1)});document.querySelectorAll(".js-next-scene").forEach(b=>b.addEventListener("click",()=>goToScene(state.currentScene+1)));el.musicButton.addEventListener("click",()=>toggleMusic());el.motionButton.addEventListener("click",()=>{state.reducedMotion=!state.reducedMotion;document.body.classList.toggle("reduce-motion",state.reducedMotion);el.motionButton.setAttribute("aria-label",state.reducedMotion?"Aktifkan animasi":"Kurangi animasi");el.motionButton.title=state.reducedMotion?"Aktifkan animasi":"Kurangi animasi";showToast(state.reducedMotion?"Animasi dikurangi.":"Animasi diaktifkan.")});el.journeyCards.forEach(c=>c.addEventListener("click",()=>openJourney(Number(c.dataset.journeyIndex))));el.calmNotes.forEach(n=>n.addEventListener("click",()=>openNote(Number(n.dataset.noteIndex))));el.fearOptions.forEach(b=>b.addEventListener("click",()=>chooseFear(b)));el.continueToLetter.addEventListener("click",()=>goToScene(4));el.letterEnvelope.addEventListener("click",openLetter);el.saveCourageButton.addEventListener("click",saveCourage);document.addEventListener("keydown",e=>{if(!state.entered)return;if(e.key==="ArrowRight"){e.preventDefault();if(state.currentScene===3&&!state.fearChosen){showToast("Pilih satu rasa takut terlebih dahulu.");return}goToScene(state.currentScene+1)}else if(e.key==="ArrowLeft"){e.preventDefault();goToScene(state.currentScene-1)}});createSceneDots();handlePhotoFallback();updateNavigation();
})();
